retab

diff --git a/git-hf-support b/git-hf-support
--- a/git-hf-support
+++ b/git-hf-support
@@ -51,137 +51,137 @@ warn "note: The support subcommand is still very EXPERIMENTAL!"
 warn "note: DO NOT use it in a production situation."
 
 usage() {
-	echo "usage: git hf support [list] [-v]"
-	echo "       git hf support start [-F] <version> <base>"
+    echo "usage: git hf support [list] [-v]"
+    echo "       git hf support start [-F] <version> <base>"
 }
 
 cmd_default() {
-	cmd_list "$@"
+    cmd_list "$@"
 }
 
 cmd_list() {
-	DEFINE_boolean verbose false 'verbose (more) output' v
-	parse_args "$@"
+    DEFINE_boolean verbose false 'verbose (more) output' v
+    parse_args "$@"
 
-	local support_branches
-	local current_branch
-	local short_names
-	support_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$support_branches" ]; then
-		warn "No support branches exist."
+    local support_branches
+    local current_branch
+    local short_names
+    support_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+    if [ -z "$support_branches" ]; then
+        warn "No support branches exist."
                 warn ""
                 warn "You can start a new support branch:"
                 warn ""
                 warn "    git hf support start <name> <base>"
                 warn ""
-		exit 0
-	fi
-	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$support_branches" | sed "s ^$PREFIX  g")
+        exit 0
+    fi
+    current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
+    short_names=$(echo "$support_branches" | sed "s ^$PREFIX  g")
 
-	# determine column width first
-	local width=0
-	local branch
-	for branch in $short_names; do
-		local len=${#branch}
-		width=$(max $width $len)
-	done
-	width=$(($width+3))
+    # determine column width first
+    local width=0
+    local branch
+    for branch in $short_names; do
+        local len=${#branch}
+        width=$(max $width $len)
+    done
+    width=$(($width+3))
 
-	local branch
-	for branch in $short_names; do
-		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-		local master_sha=$(git rev-parse "$MASTER_BRANCH")
-		local branch_sha=$(git rev-parse "$fullname")
-		if [ "$fullname" = "$current_branch" ]; then
-			printf "* "
-		else
-			printf "  "
-		fi
-		if flag verbose; then
-			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$master_sha" ]; then
-				printf "(no commits yet)"
-			else
-				local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
-				local nicename
-				if [ "$tagname" != "" ]; then
-					nicename=$tagname
-				else
-					nicename=$(git rev-parse --short "$base")
-				fi
-				printf "(based on $nicename)"
-			fi
-		else
-			printf "%s" "$branch"
-		fi
-		echo
-	done
+    local branch
+    for branch in $short_names; do
+        local fullname=$PREFIX$branch
+        local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
+        local master_sha=$(git rev-parse "$MASTER_BRANCH")
+        local branch_sha=$(git rev-parse "$fullname")
+        if [ "$fullname" = "$current_branch" ]; then
+            printf "* "
+        else
+            printf "  "
+        fi
+        if flag verbose; then
+            printf "%-${width}s" "$branch"
+            if [ "$branch_sha" = "$master_sha" ]; then
+                printf "(no commits yet)"
+            else
+                local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
+                local nicename
+                if [ "$tagname" != "" ]; then
+                    nicename=$tagname
+                else
+                    nicename=$(git rev-parse --short "$base")
+                fi
+                printf "(based on $nicename)"
+            fi
+        else
+            printf "%s" "$branch"
+        fi
+        echo
+    done
 }
 
 cmd_help() {
-	usage
-	exit 0
+    usage
+    exit 0
 }
 
 parse_args() {
-	# parse options
-	FLAGS "$@" || exit $?
-	eval set -- "${FLAGS_ARGV}"
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
 
-	# read arguments into global variables
-	VERSION=$1
-	BASE=$2
-	BRANCH=$PREFIX$VERSION
+    # read arguments into global variables
+    VERSION=$1
+    BASE=$2
+    BRANCH=$PREFIX$VERSION
 }
 
 require_version_arg() {
-	if [ "$VERSION" = "" ]; then
-		warn "Missing argument <version>"
-		usage
-		exit 1
-	fi
+    if [ "$VERSION" = "" ]; then
+        warn "Missing argument <version>"
+        usage
+        exit 1
+    fi
 }
 
 require_base_arg() {
-	if [ "$BASE" = "" ]; then
-		warn "Missing argument <base>"
-		usage
-		exit 1
-	fi
+    if [ "$BASE" = "" ]; then
+        warn "Missing argument <base>"
+        usage
+        exit 1
+    fi
 }
 
 require_base_is_on_master() {
-	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
-			| sed 's/[* ] //g' \
-	  		| grep -q "^$MASTER_BRANCH\$"; then
-		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
-	fi
+    if ! git branch --no-color --contains "$BASE" 2>/dev/null \
+            | sed 's/[* ] //g' \
+            | grep -q "^$MASTER_BRANCH\$"; then
+        die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
+    fi
 }
 
 cmd_start() {
-	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-	parse_args "$@"
-	require_version_arg
-	require_base_arg
-	require_base_is_on_master
+    DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+    parse_args "$@"
+    require_version_arg
+    require_base_arg
+    require_base_is_on_master
 
-	# sanity checks
-	require_clean_working_tree
+    # sanity checks
+    require_clean_working_tree
 
-	# fetch remote changes
-	if flag fetch; then
-		git fetch -q "$ORIGIN" "$BASE"
-	fi
-	require_branch_absent "$BRANCH"
+    # fetch remote changes
+    if flag fetch; then
+        git fetch -q "$ORIGIN" "$BASE"
+    fi
+    require_branch_absent "$BRANCH"
 
-	# create branch
-	git checkout -b "$BRANCH" "$BASE"
+    # create branch
+    git checkout -b "$BRANCH" "$BASE"
 
-	echo
-	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
-	echo "- You are now on branch '$BRANCH'"
-	echo
+    echo
+    echo "Summary of actions:"
+    echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+    echo "- You are now on branch '$BRANCH'"
+    echo
 }
diff --git a/git-hf-update b/git-hf-update
--- a/git-hf-update
+++ b/git-hf-update
@@ -46,54 +46,54 @@ require_hubflow_initialized
 hubflow_load_settings
 
 usage() {
-	echo "usage: git hf update [-p]"
+    echo "usage: git hf update [-p]"
 }
 
 parse_args() {
-	# parse options
-	FLAGS "$@" || exit $?
-	eval set -- "${FLAGS_ARGV}"
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
 }
 
 cmd_default() {
-	cmd_update "$@"
+    cmd_update "$@"
 }
 
 cmd_help() {
-	usage
-	exit 0
+    usage
+    exit 0
 }
 
 cmd_update() {
-	# flags
-	DEFINE_boolean prune true "delete local copies of branches that have been deleted from $ORIGIN" p
-	parse_args "$@"
+    # flags
+    DEFINE_boolean prune true "delete local copies of branches that have been deleted from $ORIGIN" p
+    parse_args "$@"
 
-	# make sure we're okay to start
-	require_clean_working_tree
+    # make sure we're okay to start
+    require_clean_working_tree
 
-	# fetch and merge the latest changes from origin
-	hubflow_merge_latest_changes_from_origin
+    # fetch and merge the latest changes from origin
+    hubflow_merge_latest_changes_from_origin
 
-	# make sure we end up where we should be
-	if [[ $(git_current_branch) != $BRANCH ]] ; then
-		git checkout "$BRANCH"
-	fi
+    # make sure we end up where we should be
+    if [[ $(git_current_branch) != $BRANCH ]] ; then
+        git checkout "$BRANCH"
+    fi
 
-	# drop any branches that have disappeared from origin
-	if flag prune ; then
-		git fetch --prune || die "Unable to prune branches that no longer exist at '$ORIGIN'"
-	fi
+    # drop any branches that have disappeared from origin
+    if flag prune ; then
+        git fetch --prune || die "Unable to prune branches that no longer exist at '$ORIGIN'"
+    fi
 
-	# all done
-	echo
-	echo "Summary of actions:"
-	echo "- Any changes to branches at $ORIGIN have been downloaded to your local repository"
-	if flag prune ; then
-		echo "- Any branches that have been deleted at $ORIGIN have also been deleted from your local repository"
-	fi
-	echo "- Any changes from $ORIGIN/$MASTER_BRANCH have been merged into branch '$MASTER_BRANCH'"
-	echo "- Any changes from $ORIGIN/$DEVELOP_BRANCH have been merged into branch '$DEVELOP_BRANCH'"
-	echo "- Any resolved merge conflicts have been pushed back to $ORIGIN"
-	echo "- You are now on branch '$BRANCH'"
+    # all done
+    echo
+    echo "Summary of actions:"
+    echo "- Any changes to branches at $ORIGIN have been downloaded to your local repository"
+    if flag prune ; then
+        echo "- Any branches that have been deleted at $ORIGIN have also been deleted from your local repository"
+    fi
+    echo "- Any changes from $ORIGIN/$MASTER_BRANCH have been merged into branch '$MASTER_BRANCH'"
+    echo "- Any changes from $ORIGIN/$DEVELOP_BRANCH have been merged into branch '$DEVELOP_BRANCH'"
+    echo "- Any resolved merge conflicts have been pushed back to $ORIGIN"
+    echo "- You are now on branch '$BRANCH'"
 }
